/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Midorisour Playground FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnimalHouseCommonResponse,
  AnimalHouseUnusualResponse
} from './model';

/**
 * @summary Healthcheck
 */
export type healthcheckHealthcheckGetResponse200 = {
  data: unknown
  status: 200
}
    
export type healthcheckHealthcheckGetResponseSuccess = (healthcheckHealthcheckGetResponse200) & {
  headers: Headers;
};
;

export type healthcheckHealthcheckGetResponse = (healthcheckHealthcheckGetResponseSuccess)

export const getHealthcheckHealthcheckGetUrl = () => {


  

  return `https://api.midorisour.kro.kr/healthcheck`
}

export const healthcheckHealthcheckGet = async ( options?: RequestInit): Promise<healthcheckHealthcheckGetResponse> => {
  
  const res = await fetch(getHealthcheckHealthcheckGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthcheckHealthcheckGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthcheckHealthcheckGetResponse
}



/**
 * @summary Get Common Response
 */
export type getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponse200 = {
  data: AnimalHouseCommonResponse
  status: 200
}
    
export type getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponseSuccess = (getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponse200) & {
  headers: Headers;
};
;

export type getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponse = (getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponseSuccess)

export const getGetCommonResponseWorkingWithFrontendUnionCommonResponseGetUrl = () => {


  

  return `https://api.midorisour.kro.kr/working-with-frontend/union/common-response`
}

export const getCommonResponseWorkingWithFrontendUnionCommonResponseGet = async ( options?: RequestInit): Promise<getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponse> => {
  
  const res = await fetch(getGetCommonResponseWorkingWithFrontendUnionCommonResponseGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCommonResponseWorkingWithFrontendUnionCommonResponseGetResponse
}



/**
 * @summary Get Unusual Response
 */
export type getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponse200 = {
  data: AnimalHouseUnusualResponse
  status: 200
}
    
export type getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponseSuccess = (getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponse200) & {
  headers: Headers;
};
;

export type getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponse = (getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponseSuccess)

export const getGetUnusualResponseWorkingWithFrontendUnionUnusualResponseGetUrl = () => {


  

  return `https://api.midorisour.kro.kr/working-with-frontend/union/unusual-response`
}

export const getUnusualResponseWorkingWithFrontendUnionUnusualResponseGet = async ( options?: RequestInit): Promise<getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponse> => {
  
  const res = await fetch(getGetUnusualResponseWorkingWithFrontendUnionUnusualResponseGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUnusualResponseWorkingWithFrontendUnionUnusualResponseGetResponse
}
