/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Midorisour Playground FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Cat } from './cat';
import type { Dog } from './dog';

export type AnimalHouseUnusualResponseMammalia = Cat | Dog;
