/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Midorisour Playground FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { AnimalHouseCommonResponseCreature } from './animalHouseCommonResponseCreature';
import type { AnimalHouseCommonResponseMammalia } from './animalHouseCommonResponseMammalia';

export interface AnimalHouseCommonResponse {
  creature: AnimalHouseCommonResponseCreature;
  mammalia: AnimalHouseCommonResponseMammalia;
}
