/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Midorisour Playground FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { AnimalHouseUnusualResponseCreature } from './animalHouseUnusualResponseCreature';
import type { AnimalHouseUnusualResponseMammalia } from './animalHouseUnusualResponseMammalia';

export interface AnimalHouseUnusualResponse {
  creature: AnimalHouseUnusualResponseCreature;
  mammalia: AnimalHouseUnusualResponseMammalia;
}
