/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Midorisour Playground FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Ant } from './ant';

export interface Ants {
  /** List of Ant */
  ant_list: Ant[];
}
