/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Midorisour Playground FastAPI
 * OpenAPI spec version: 1.0.0
 */

export * from './animalHouseCommonResponse';
export * from './animalHouseCommonResponseCreature';
export * from './animalHouseCommonResponseMammalia';
export * from './animalHouseUnusualResponse';
export * from './animalHouseUnusualResponseCreature';
export * from './animalHouseUnusualResponseMammalia';
export * from './ant';
export * from './ants';
export * from './bee';
export * from './cat';
export * from './dog';